# Generated by Django 3.2.9 on 2022-06-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuerpo_técnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('FNacimiento', models.DateField(blank=True, null=True)),
                ('Nacionalidad', models.CharField(max_length=200)),
                ('Rol', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Equipo', models.CharField(max_length=200)),
                ('Imagen', models.CharField(max_length=200)),
                ('Escudo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto', models.CharField(max_length=200)),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('Fnacimiento', models.DateField(blank=True, null=True)),
                ('Posición', models.CharField(max_length=20)),
                ('NCamiseta', models.CharField(max_length=5)),
                ('titular', models.CharField(max_length=50)),
            ],
        ),
    ]
