# Generated by Django 3.2.9 on 2022-06-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuerpo_técnico',
            name='Apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cuerpo_técnico',
            name='Nacionalidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cuerpo_técnico',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cuerpo_técnico',
            name='Rol',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Escudo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Imagen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Nombre_Equipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='Apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='Foto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
    ]
