# Generated by Django 3.2.9 on 2022-06-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220603_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='Edad',
            field=models.PositiveIntegerField(default=0, verbose_name='edad'),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='idEquipo',
            field=models.PositiveIntegerField(default=0, verbose_name='id equipo'),
        ),
    ]
