# Generated by Django 3.2.9 on 2022-06-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220603_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuerpo_técnico',
            name='idEquipo',
            field=models.PositiveIntegerField(default=0, verbose_name='id equipo'),
        ),
    ]
